basePath: /api/v1
definitions:
  auth.RsGoogleAuthURL:
    properties:
      url:
        type: string
    type: object
  auth.RsToken:
    properties:
      access_token:
        type: string
      is_superadmin:
        type: boolean
      refresh_token:
        type: string
    type: object
  auth.RsUser:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_superadmin:
        type: boolean
      last_name:
        type: string
      phone:
        type: string
      updated_at:
        type: string
    type: object
  response.RsError:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: internal server error
        type: string
    type: object
  setting.RsPractitioner:
    properties:
      abn:
        type: string
      created_at:
        type: string
      id:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
      verified:
        type: boolean
    type: object
  setting.RsPractitionerSetting:
    properties:
      color:
        type: string
      created_at:
        type: string
      id:
        type: integer
      logo:
        type: string
      practitioner_id:
        type: string
      timezone:
        type: string
      updated_at:
        type: string
    type: object
  subscription.RsSubscription:
    properties:
      created_at:
        type: string
      description:
        type: string
      duration_days:
        type: integer
      id:
        type: integer
      is_active:
        type: boolean
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: Backend API for acareca
  title: Backend API
  version: 1.0.0
paths:
  /admin/subscription:
    get:
      consumes:
      - application/json
      description: list subscriptions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscription.RsSubscription'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: List subscriptions
      tags:
      - subscription
    post:
      consumes:
      - application/json
      description: create a new subscription
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscription.RsSubscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Create a new subscription
      tags:
      - subscription
  /admin/subscription/{id}:
    delete:
      consumes:
      - application/json
      description: delete a subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Delete a subscription
      tags:
      - subscription
    get:
      consumes:
      - application/json
      description: get a subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscription.RsSubscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Get a subscription
      tags:
      - subscription
    put:
      consumes:
      - application/json
      description: update a subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscription.RsSubscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Update a subscription
      tags:
      - subscription
  /auth/google:
    get:
      description: get Google OAuth consent-screen URL
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RsGoogleAuthURL'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Get Google OAuth consent-screen URL
      tags:
      - auth
  /auth/google/callback:
    get:
      description: handle Google OAuth callback
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RsToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Handle Google OAuth callback
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: login a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RsToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Login a user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: register a new user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RsUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Register a new user
      tags:
      - auth
  /practitioner:
    get:
      consumes:
      - application/json
      description: list practitioners
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setting.RsPractitioner'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: List practitioners
      tags:
      - practitioner
    post:
      consumes:
      - application/json
      description: create a new practitioner
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setting.RsPractitioner'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Create a new practitioner
      tags:
      - practitioner
  /practitioner/{id}:
    delete:
      consumes:
      - application/json
      description: delete a practitioner
      parameters:
      - description: Practitioner ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Delete a practitioner
      tags:
      - practitioner
    get:
      consumes:
      - application/json
      description: get a practitioner by ID
      parameters:
      - description: Practitioner ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setting.RsPractitioner'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Get a practitioner by ID
      tags:
      - practitioner
    put:
      consumes:
      - application/json
      description: update a practitioner
      parameters:
      - description: Practitioner ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setting.RsPractitioner'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Update a practitioner
      tags:
      - practitioner
  /practitioner/setting/{id}:
    get:
      consumes:
      - application/json
      description: get a setting by practitioner ID
      parameters:
      - description: Practitioner ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setting.RsPractitionerSetting'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Get a setting by practitioner ID
      tags:
      - setting
    put:
      consumes:
      - application/json
      description: upsert a setting by practitioner ID
      parameters:
      - description: Practitioner ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setting.RsPractitionerSetting'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Upsert a setting by practitioner ID
      tags:
      - setting
  /practitioner/subscription:
    get:
      consumes:
      - application/json
      description: list subscriptions by practitioner ID
      parameters:
      - description: Practitioner ID
        in: path
        name: practitioner_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscription.RsSubscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: List subscriptions by practitioner ID
      tags:
      - subscription
  /practitioner/subscription/{id}:
    delete:
      consumes:
      - application/json
      description: delete a subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      - description: Practitioner ID
        in: path
        name: practitioner_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Delete a subscription
      tags:
      - subscription
    get:
      consumes:
      - application/json
      description: get a subscription by ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscription.RsSubscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Get a subscription by ID
      tags:
      - subscription
    put:
      consumes:
      - application/json
      description: update a subscription
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      - description: Practitioner ID
        in: path
        name: practitioner_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscription.RsSubscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Update a subscription
      tags:
      - subscription
  /practitioner/user/{user_id}:
    get:
      consumes:
      - application/json
      description: get a practitioner by user ID
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/setting.RsPractitioner'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.RsError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.RsError'
      summary: Get a practitioner by user ID
      tags:
      - practitioner
schemes:
- http
swagger: "2.0"
