package formula

import (
	"testing"
)

func TestPipeline_JSON_to_Result(t *testing.T) {
	// Expected architecture:
	//
	//   JSON Formula
	//       │
	//       ▼
	//     Parser  (JSON → Expression DTO → AST)
	//       │
	//       ▼
	//     AST (Expression Tree)
	//       │
	//       ├── Validator
	//       │
	//       └── Evaluator
	//               │
	//               ▼
	//             Result

	t.Run("full pipeline: JSON → Parse → Validate → Evaluate → Result", func(t *testing.T) {
		// ── Step 1: Input (JSON Formula) ────────────────────────────
		jsonInput := []byte(`{
			"type": "operator",
			"op": "+",
			"left": {
				"type": "operator",
				"op": "*",
				"left": { "type": "field", "key": "income" },
				"right": { "type": "constant", "value": 0.60 }
			},
			"right": { "type": "constant", "value": 100 }
		}`)

		// ── Step 2: Parse (JSON → AST) ──────────────────────────────
		parser := NewJSONParser()
		evaluator, err := parser.Parse(jsonInput)
		if err != nil {
			t.Fatalf("Parse failed: %v", err)
		}
		if evaluator == nil {
			t.Fatal("Parse returned nil evaluator (AST root)")
		}

		// ── Step 3: Validate (AST checks) ───────────────────────────
		allowedFields := []string{"income", "expenses"}
		validator := NewValidator(allowedFields)

		err = validator.Validate(evaluator)
		if err != nil {
			t.Fatalf("Validate failed: %v", err)
		}

		// ── Step 4: Evaluate (walk AST → compute result) ────────────
		ctx := Context{
			Values: map[string]float64{
				"income": 10000,
			},
		}

		result, err := evaluator.Evaluate(ctx)
		if err != nil {
			t.Fatalf("Evaluate failed: %v", err)
		}

		// (income × 0.60) + 100 = (10000 × 0.60) + 100 = 6000 + 100 = 6100
		expected := 6100.0
		if result != expected {
			t.Fatalf("Expected %.2f, got %.2f", expected, result)
		}

		// ── Verify AST structure ────────────────────────────────────
		// The evaluator is the root AST node. Verify it's an AddNode.
		addNode, ok := evaluator.(*AddNode)
		if !ok {
			t.Fatal("Root AST node should be *AddNode for '+' operator")
		}

		// Left child should be MultiplyNode
		mulNode, ok := addNode.Left.(*MultiplyNode)
		if !ok {
			t.Fatal("Left child of AddNode should be *MultiplyNode")
		}

		// Right child should be ConstantNode (value = 100)
		constNode, ok := addNode.Right.(*ConstantNode)
		if !ok {
			t.Fatal("Right child of AddNode should be *ConstantNode")
		}
		if constNode.Value != 100 {
			t.Fatalf("Expected constant value 100, got %f", constNode.Value)
		}

		// MultiplyNode left should be FieldNode("income")
		fieldNode, ok := mulNode.Left.(*FieldNode)
		if !ok {
			t.Fatal("Left child of MultiplyNode should be *FieldNode")
		}
		if fieldNode.Key != "income" {
			t.Fatalf("Expected field key 'income', got '%s'", fieldNode.Key)
		}

		// MultiplyNode right should be ConstantNode(0.60)
		rateNode, ok := mulNode.Right.(*ConstantNode)
		if !ok {
			t.Fatal("Right child of MultiplyNode should be *ConstantNode")
		}
		if rateNode.Value != 0.60 {
			t.Fatalf("Expected constant value 0.60, got %f", rateNode.Value)
		}
	})
}

func TestPipeline_ValidationErrors(t *testing.T) {
	tests := []struct {
		name    string
		json    []byte
		wantErr error
	}{
		{
			name:    "nil node should fail validation",
			json:    nil,
			wantErr: ErrNilNode,
		},
		{
			name: "invalid field should fail validation",
			json: []byte(`{
				"type": "field",
				"key": "nonexistent"
			}`),
			wantErr: ErrInvalidField,
		},
		{
			name: "division by zero constant should fail validation",
			json: []byte(`{
				"type": "operator",
				"op": "/",
				"left": { "type": "constant", "value": 100 },
				"right": { "type": "constant", "value": 0 }
			}`),
			wantErr: ErrDivisionByZero,
		},
		{
			name: "missing left operand should fail during parse",
			json: []byte(`{
				"type": "operator",
				"op": "+",
				"left": null,
				"right": { "type": "constant", "value": 5 }
			}`),
			wantErr: ErrMissingOperand,
		},
		{
			name: "unsupported operator should fail during parse",
			json: []byte(`{
				"type": "operator",
				"op": "^",
				"left": { "type": "constant", "value": 1 },
				"right": { "type": "constant", "value": 2 }
			}`),
			wantErr: nil, // handled separately
		},
		{
			name:    "unsupported node type should fail during parse",
			json:    []byte(`{ "type": "unknown" }`),
			wantErr: nil, // handled separately
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.json == nil {
				validator := NewValidator([]string{"a"})
				err := validator.Validate(nil)
				if err != tt.wantErr {
					t.Fatalf("Expected %v, got %v", tt.wantErr, err)
				}
				return
			}

			// Handle special cases where parse error is generated by parser itself
			// (not using validator sentinel errors)
			if tt.name == "unsupported operator should fail during parse" {
				parser := NewJSONParser()
				_, err := parser.Parse(tt.json)
				if err == nil {
					t.Fatal("Expected parse error for unsupported operator")
				}
				return
			}
			if tt.name == "unsupported node type should fail during parse" {
				parser := NewJSONParser()
				_, err := parser.Parse(tt.json)
				if err == nil {
					t.Fatal("Expected parse error for unsupported node type")
				}
				if err.Error() != "unsupported type: unknown" {
					t.Fatalf("Expected 'unsupported type: unknown', got %v", err)
				}
				return
			}

			parser := NewJSONParser()
			evaluator, err := parser.Parse(tt.json)

			// Some errors surface during parsing (nil child)
			if err != nil {
				if !containsError(err, tt.wantErr) {
					t.Fatalf("Parse error: expected containing %v, got %v", tt.wantErr, err)
				}
				return
			}

			validator := NewValidator([]string{"a", "b", "c"})
			err = validator.Validate(evaluator)

			if err == nil {
				t.Fatal("Expected validation error, got nil")
			}

			if !containsError(err, tt.wantErr) {
				t.Fatalf("Expected error containing %v, got %v", tt.wantErr, err)
			}
		})
	}
}

func TestPipeline_EvaluationErrors(t *testing.T) {
	t.Run("missing field should fail evaluation", func(t *testing.T) {
		jsonInput := []byte(`{
			"type": "field",
			"key": "income"
		}`)

		parser := NewJSONParser()
		evaluator, err := parser.Parse(jsonInput)
		if err != nil {
			t.Fatalf("Parse failed: %v", err)
		}

		ctx := Context{
			Values: map[string]float64{
				"other": 100,
			},
		}

		_, err = evaluator.Evaluate(ctx)
		if err == nil {
			t.Fatal("Expected error for missing field, got nil")
		}
	})

	t.Run("division by zero at runtime", func(t *testing.T) {
		// Runtime division by zero passes static validation (RHS is a field, not constant)
		// but produces +Inf at evaluation time (Go float64 behavior)
		jsonInput := []byte(`{
			"type": "operator",
			"op": "/",
			"left": { "type": "constant", "value": 100 },
			"right": { "type": "field", "key": "x" }
		}`)

		parser := NewJSONParser()
		evaluator, err := parser.Parse(jsonInput)
		if err != nil {
			t.Fatalf("Parse failed: %v", err)
		}

		// Validate passes because RHS is a field, not a constant 0
		validator := NewValidator([]string{"x"})
		if err := validator.Validate(evaluator); err != nil {
			t.Fatalf("Validate should pass for field-based divisor: %v", err)
		}

		// Evaluate returns +Inf for 100/0 (Go float64 behavior)
		ctx := Context{Values: map[string]float64{"x": 0}}
		result, err := evaluator.Evaluate(ctx)
		if err != nil {
			t.Fatalf("Evaluate should not return error for Go float64 div/0: %v", err)
		}
		if !isInf(result) {
			t.Fatalf("Expected +Inf for 100/0, got %f", result)
		}
	})
}

func TestPipeline_AllOperatorTypes(t *testing.T) {
	tests := []struct {
		name     string
		json     []byte
		expected float64
	}{
		{
			name: "addition",
			json: []byte(`{
				"type": "operator", "op": "+",
				"left": { "type": "constant", "value": 100 },
				"right": { "type": "constant", "value": 50 }
			}`),
			expected: 150,
		},
		{
			name: "subtraction",
			json: []byte(`{
				"type": "operator", "op": "-",
				"left": { "type": "constant", "value": 100 },
				"right": { "type": "constant", "value": 50 }
			}`),
			expected: 50,
		},
		{
			name: "multiplication",
			json: []byte(`{
				"type": "operator", "op": "*",
				"left": { "type": "constant", "value": 100 },
				"right": { "type": "constant", "value": 0.60 }
			}`),
			expected: 60,
		},
		{
			name: "division",
			json: []byte(`{
				"type": "operator", "op": "/",
				"left": { "type": "constant", "value": 100 },
				"right": { "type": "constant", "value": 5 }
			}`),
			expected: 20,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			parser := NewJSONParser()
			evaluator, err := parser.Parse(tt.json)
			if err != nil {
				t.Fatalf("Parse failed: %v", err)
			}

			validator := NewValidator([]string{})
			if err := validator.Validate(evaluator); err != nil {
				t.Fatalf("Validate failed: %v", err)
			}

			ctx := Context{Values: map[string]float64{}}
			result, err := evaluator.Evaluate(ctx)
			if err != nil {
				t.Fatalf("Evaluate failed: %v", err)
			}
			if result != tt.expected {
				t.Fatalf("Expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestPipeline_BasCodeExpression(t *testing.T) {
	// User's exact payload:
	//   (G1 - 1A) - D
	// Where G1=5000, 1A=300, D=200
	// Result: (5000 - 300) - 200 = 4500
	jsonInput := []byte(`{
		"type": "operator",
		"op": "-",
		"left": {
			"type": "operator",
			"op": "-",
			"left": {
				"type": "bas_code",
				"key": "G1"
			},
			"right": {
				"type": "bas_code",
				"key": "1A"
			}
		},
		"right": {
			"type": "field",
			"key": "D"
		}
	}`)

	parser := NewJSONParser()
	evaluator, err := parser.Parse(jsonInput)
	if err != nil {
		t.Fatalf("Parse failed: %v", err)
	}

	validator := NewValidator([]string{"D"})
	if err := validator.Validate(evaluator); err != nil {
		t.Fatalf("Validate failed: %v", err)
	}

	ctx := Context{
		Values: map[string]float64{
			"G1": 5000,
			"1A": 300,
			"D":  200,
		},
	}

	// Test via BuildFormula
	result, err := BuildFormula(ctx, jsonInput)
	if err != nil {
		t.Fatalf("BuildFormula failed: %v", err)
	}

	expected := 4500.0
	if result != expected {
		t.Fatalf("Expected %v, got %v", expected, result)
	}

	// ── Verify AST structure ────────────────────────────────────
	// Root should be SubtractNode (outer "-")
	outerSub, ok := evaluator.(*SubtractNode)
	if !ok {
		t.Fatal("Root AST node should be *SubtractNode")
	}

	// Left of root should be SubtractNode (inner "-")
	innerSub, ok := outerSub.Left.(*SubtractNode)
	if !ok {
		t.Fatal("Left child should be *SubtractNode for inner '-'")
	}

	// innerSub.Left should be BasCodeNode("G1")
	g1Node, ok := innerSub.Left.(*BasCodeNode)
	if !ok {
		t.Fatal("Left of inner '-' should be *BasCodeNode")
	}
	if g1Node.Key != "G1" {
		t.Fatalf("Expected bas code 'G1', got '%s'", g1Node.Key)
	}

	// innerSub.Right should be BasCodeNode("1A")
	iaNode, ok := innerSub.Right.(*BasCodeNode)
	if !ok {
		t.Fatal("Right of inner '-' should be *BasCodeNode")
	}
	if iaNode.Key != "1A" {
		t.Fatalf("Expected bas code '1A', got '%s'", iaNode.Key)
	}

	// Right of root should be FieldNode("D")
	dNode, ok := outerSub.Right.(*FieldNode)
	if !ok {
		t.Fatal("Right of root '-' should be *FieldNode")
	}
	if dNode.Key != "D" {
		t.Fatalf("Expected field key 'D', got '%s'", dNode.Key)
	}
}

func TestPipeline_ComplexNestedExpression(t *testing.T) {
	// Formula: (income - expenses) * (1 - tax_rate) + bonus
	// Where: income=10000, expenses=2000, tax_rate=0.30, bonus=500
	// Result: (10000 - 2000) * (1 - 0.30) + 500 = 8000 * 0.70 + 500 = 5600 + 500 = 6100
	jsonInput := []byte(`{
		"type": "operator", "op": "+",
		"left": {
			"type": "operator", "op": "*",
			"left": {
				"type": "operator", "op": "-",
				"left": { "type": "field", "key": "income" },
				"right": { "type": "field", "key": "expenses" }
			},
			"right": {
				"type": "operator", "op": "-",
				"left": { "type": "constant", "value": 1 },
				"right": { "type": "field", "key": "tax_rate" }
			}
		},
		"right": { "type": "field", "key": "bonus" }
	}`)

	parser := NewJSONParser()
	evaluator, err := parser.Parse(jsonInput)
	if err != nil {
		t.Fatalf("Parse failed: %v", err)
	}

	validator := NewValidator([]string{"income", "expenses", "tax_rate", "bonus"})
	if err := validator.Validate(evaluator); err != nil {
		t.Fatalf("Validate failed: %v", err)
	}

	ctx := Context{
		Values: map[string]float64{
			"income":   10000,
			"expenses": 2000,
			"tax_rate": 0.30,
			"bonus":    500,
		},
	}

	result, err := evaluator.Evaluate(ctx)
	if err != nil {
		t.Fatalf("Evaluate failed: %v", err)
	}

	expected := 6100.0
	if result != expected {
		t.Fatalf("Expected %v, got %v", expected, result)
	}
}

// ─── helpers ──────────────────────────────────────────────────────────────────

func containsError(err error, target error) bool {
	if err == target {
		return true
	}
	for err != nil {
		if err == target {
			return true
		}
		if unwrapper, ok := err.(interface{ Unwrap() error }); ok {
			err = unwrapper.Unwrap()
		} else {
			return false
		}
	}
	return false
}

func isInf(v float64) bool {
	return v > 1e300 || v < -1e300
}
